name: sampark
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  slide_to_act: ^2.0.2
  get: ^4.6.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  image_picker: ^1.1.2
  firebase_storage: ^11.6.0
  uuid: ^4.4.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/Fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Fonts/Poppins-ExtraBold.ttf
          weight: 800
